export { default as AboutPage } from './About'
export { default as ContactPage } from './Contact'
export { default as HomePage } from './Home'
export { default as Page404 } from './Page404'
export { default as RemoveDuplicatePage } from './RemoveDuplicate'
export { default as TestPage } from './Test'
